services:
  backend:
    build: ./app
    network_mode: host
    volumes:
      - '/opt/temp-file-share/uploads:/app/uploads'
      - '/opt/temp-file-share/data:/app/data'
    container_name: temp-file-share
    restart: unless-stopped
    environment:
      TZ: Asia/Colombo
